services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: soybean-admin-backend
            POSTGRES_USER: soybean
            POSTGRES_PASSWORD: soybean@123.
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - backend

    redis:
        image: redis:7.4.1
        volumes:
            - redisdata:/data
        ports:
            - "6379:6379"
        networks:
            - backend

    mongo:
        image: mongo:8.0.3
        #        environment:
        #            MONGO_INITDB_ROOT_USERNAME: user
        #            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
        networks:
            - backend

    kafka:
        image: confluentinc/cp-kafka:7.7.1
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_NODE_ID: 1
            KAFKA_CLUSTER_ID: 'q1Sh-9_ISia_zwGINzRvyQ'
            KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            KAFKA_QUORUM_CONTROLLER_PORT: 29093
            KAFKA_QUORUM_CONTROLLER_PROTOCOL: PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_NUM_NETWORK_THREADS: 3
            KAFKA_NUM_IO_THREADS: 8
            KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
            KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
            KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
            KAFKA_LOG_DIRS: "/var/lib/kafka/data"
            CLUSTER_ID: 'q1Sh-9_ISia_zwGINzRvyQ'
        volumes:
            - kafkadata:/var/lib/kafka/data
        networks:
            - backend

volumes:
    pgdata:
    redisdata:
    mongodata:
    kafkadata:

networks:
    backend:
        driver: bridge
